### ISSUE TITLE
pth links broken

### ISSUE THREAD

**Issue by learnermaxRL** [cscribano/CERBERUS#3]
Hi cant find the pth files in the link,kindly fix

**Comment by cscribano** [comment]
They all appear to be working, please paste the link that you are having issues with.

**Comment by learnermaxRL** [comment]
earlier it was downloading the pth file ,,but now its pointing towards a zip folder with pkl files in it,cant find pth model int it

**Comment by cscribano** [comment]
You are looking at the content of the pht archive, just download the whole package from the top-right menu.
