### ISSUE TITLE
cannot inference with inference/run.py

### ISSUE THREAD

**Issue by dotrannhattuong** [cscribano/CERBERUS#5]
Traceback (most recent call last):
  File "inference/run.py", line 19, in <module>
    from dataset.utils.transforms import Preproc
ModuleNotFoundError: No module named 'dataset'

**Comment by cscribano** [comment]
I'm not able to reproduce your issue.
Are you running the python interpreter from inside the root directory of this repo?

Please provide additional details: Operative System, Python version, current environment (assuming you are using anaconda)

**Comment by dotrannhattuong** [comment]
Ubuntu: 18.04
Python: 3.8
Env: anaconda

Run command: python inference/run.py -c resnet34_simple.json -w resnet34_simple.pth -v dashcam_demo.mp4

**Comment by cscribano** [comment]
Mr dotrannhattuong.
I've seen that you created a repository which contains 100% of my code **stolen** from my repository, without even acknowledging our work. 

No help will be given to you, good luck.

**Comment by dotrannhattuong** [comment]
I'm really sorry that I don't understand intellectual property rights very well.

I use it for study and research purposes only. I will cite your paper. Thanks
