### ISSUE TITLE
How to train own data？

### ISSUE THREAD

**Issue by jing-turing** [cscribano/CERBERUS#6]
Thank you for the author's contribution. In this framework, It was very easy and effective to use the BDD100K open dataset for training. Therefore, I would like to further fine-tune the model using actual experimental scene data. The annotation work for object detection and scene classification can be done easily in the format of BDD100K. 
However, I would like to ask for the author's suggestion on how to annotate road lines for lane detection in a proper way?

**Comment by cscribano** [comment]
Thank you for your interest! To annotate lane lines we strongly recommend Scalabel (https://github.com/scalabel/scalabel). This Is the same tool used for the creation of BDD100K, hence It will be simple to modify the preprocessing code for the new annotations. I've personally done some annotation and training this very model on custom annotation.
